### ISSUE TITLE
can't find project root Error

### ISSUE THREAD

**Issue by lambdacoresw** [remvee/android-mode#50]
I got this error after I entering path, package, activity inputs.  I correctly entered andorid-sdk path. 

How can I solve this problem?
Thanks

**Comment by wizmer** [comment]
First you have to choose you builder by customizing the android-mode-builder variable.
For example, for me the builder is 'adb' so in my custom-set-variables I have:
 **'(android-mode-builder (quote adb))** 
but you can also set maven, ant or gradle.

Now you have to set the file that will be used as the root directory of your builder. It is the variable android-mode-root-file-plist. It contains a mapping for each build between the builder and a file that is in the folder from which the builder has to run.

The default is:
 '(android-mode-root-file-plist
   (quote
    (ant "AndroidManifest.xml" gradle "build.gradle" maven "AndroidManifest.xml" )))

As you can see, for me using adb, I have to add a mapping 'adb -> adbFile' because it is not there. I know my adb command must run from the foler containing the file gradlew so I put:

 '(android-mode-root-file-plist
   (quote
    (ant "AndroidManifest.xml" gradle "build.gradle" maven "AndroidManifest.xml" **adb "gradlew"**)))

and it worked ;-)

**Comment by lambdacoresw** [comment]
Nope, the problem continues...

**Comment by iUwej** [comment]
@wizmer solution resolves this issue. You have to change both the android-mode-builder variable 
**(android-mode-builder 'gradle)** . Make sure you also change the android-mode-root-file-plist gradle entry from gradle "build.gradle" to gradle "gradlew" as in
**(android-mode-root-file-plist  '(ant "AndroidManifest.xml" gradle "gradlew" maven "AndroidManifest")**

Without changing the both the entries , the build will still fail

**Comment by dudelson** [comment]
I am also having @lambdacoresw's issue. To be clear, this is not an issue when building the project, it's an issue when creating a new project via `M-x android-create-project`. The crux of the problem appears to be that `android-create-project` indirectly ends up calling `android-in-root`, which assumes a project exists, otherwise it fails with the error "can't find project root". I am new to both this project and emacs lisp, but I will try to submit a PR that fixes this issue this weekend. For the time being, the best workaround IMO is to simply create projects from the command line with `android create project`.

**Comment by remvee** [comment]
Sorry for the late reply, I haven't been doing android development for a long time now.  I've noticed gradle is the default build system nowadays.  So let's make `'gradle` the default for `android-mode-builder` and fix the `android-mode-root-file-plist` as @wizmer suggested.  Can somebody bake me a PR for that?

One thing to note the `dired-mode-hook` and `find-file-hook` will cause `android-mode` to be turned on for all gradle projects.  That's probably not very nice..  So proper gradle support needs more work.

As for `android-create-project`, let's drop that.  It's kinda pointless.  Anybody who can do android development in emacs, can run it from the command line and is probably already doing that.

**Comment by wuqian** [comment]
my pull request will solve this problem.

**Comment by tobiasBora** [comment]
Any news for that bug which is still present in the marmalade repo ?

**Comment by remvee** [comment]
I haven't done any Andriod development in years and need to setup the android SDK, make a test project just to figure out what is exactly wrong and how to fix it properly.

Here's me hoping somebody steps up to make me a PR to solve this. 🙏  I'll be happy to add you as a collaborator when you do.

**Comment by ejmg** [comment]
I'm wanting to get into android dev and would prefer to stay within my emacs/spacemacs work environment. I have a clean install of android sdk and am experiencing the exact same problem. What should be looked at? I'm willing to help if I can.

**Comment by remvee** [comment]
@ejmg thanks and yes please help is very welcome!

I'll close this issue, hoping PR #53 fixes it.
